# Worker Configuration

```toml
name = "acuityacademy"
compatibility_date = "2026-03-25"

[[env]]
  key = "VAR1"
  value = "value1"

[[env]]
  key = "VAR2"
  value = "value2"

[[bindings.kv]]
  binding = "KV_NAMESPACE_NAME"
  id = "kv-namespace-id"

[[bindings.r2]]
  binding = "R2_BINDING_NAME"
  bucket = "r2-bucket-name"

[[database.d1]]
  binding = "D1_DATABASE_BINDING"
  database = "d1-database-name"

# Production Environment Configuration
[env.production]
VAR1 = "prod_value1"
VAR2 = "prod_value2"

# Development Environment Configuration
[env.development]
VAR1 = "dev_value1"
VAR2 = "dev_value2"
```
